###########
# General #
###########
general:
  language: 'en'
  storage: 'file'
  saveInterval: 30

###########
#  Mysql  #
###########
mysql:
  host: 'localhost'
  port: 3306
  database: 'test'
  user: 'user'
  password: 'pw'
  tablePrefix: 'lori_time'

###################
#  Do not touch!  #
##################
configVersion: 1
