###########
# General #
###########
general:

  # Default Language of the unit-modifier and the command responses for the player.
  # To see all available options see: https://github.com/Lorias-Jak/LoriTime/tree/main/src/main/resources/localization
  language: 'en'

  # You can decide how the player data will be stored.
  # The two options are 'yml' or 'mysql'.
  storage: 'yml'

  # The save interval specifies how often the player's online time is saved.
  # The unit is seconds.
  saveInterval: 30

##############
# MultiSetup #
##############
multiSetup:
  enabled: false
  mode: 'master'

###########
#  Mysql  #
###########
mysql:
  host: 'localhost'
  port: 3306
  database: 'test'
  user: 'user'
  password: 'pw'
  tablePrefix: 'lori_time'

###########
#   AFK   #
###########
afk:
  enabled: false
  after: '15m'
  removeTime: true
  autoKick: true

###################
#  Do not touch!  #
##################
configVersion: 2
