###########
# General #
###########
general:

  # If true, the plugin debugger will be enabled.
  # This will print out more information in the console.
  # Do not let this enabled, it will spam your console.
  # This Config option has to be set manually! You cant change this via the in-game command!
  debug: false

  # The time after wich the debugger will be disabled automatically.
  # Set this to -1 to disable the auto-disable function of the debugger.
  # The unit for this is minutes.
  debugAutoDisableTime: 30

  # Default Language of the unit-modifier and the command responses for the player.
  # To see all available options see: https://github.com/Lorias-Jak/LoriTime/tree/main/src/main/resources/localization
  language: 'en'

  # You can decide how the player data will be stored.
  # The two options are 'yml' or 'mysql'.
  storage: 'yml'

  # The save interval specifies how often the player's online time is saved.
  # The unit is seconds.
  saveInterval: 30

###########
# Updater #
###########
updater:

  # LoriTime will automatically check for Updates on Modrinth or GitHub.
  # In case you use the multi-setup this will only be checked on the master.
  # If you want to disable this feature, set this to false.
  checkForUpdates: true

  # The Strategy for the update command.
  # Available options are 'MAJOR', 'MINOR', 'PATCH' in the format MAJOR.MINOR.PATCH (e.g. 1.2.5)
  updateStrategy: 'MINOR'

  # If the plugin should update itself automatically if a new release version is available.
  # This will respect the updateStrategy that you have set above.
  autoUpdate: false

  # If true, the plugin will send a message to the player if a new version is available.
  # The message will only appear on server join.
  # It will only be sent once every 24 hours or after a server restart.
  inGameNotification: true

###########
# Backups #
###########
backup:

  # If true, the plugin will create backups every time the config or language files got an update.
  enabled: true

  # The maximum number of backups that will be stored.
  # If the number of backups exceeds this value, the oldest backup will be deleted.
  # Set this to 0 to disable the deletion of old backups.
  maxBackups: 5

###########
#  Mysql  #
###########
mysql:
  host: 'localhost'
  port: 3306
  database: 'test'
  user: 'user'
  password: 'pw'
  tablePrefix: 'lori_time'

##############
# MultiSetup #
##############
multiSetup:

  # If true, the plugin will be enabled for multiple server setup.
  # Only activate and set on master on proxy-server, use the slave mode on sub-servers.
  enabled: false

  # Options to set: "master", "slave".
  mode: 'master'

###########
#   AFK   #
###########
afk:

  # In case you're using MultiSetup, this will change nothing for proxys.
  # Do not change the value while the server is running!
  # The required classes will not be loaded if this option is false on startup.
  # If you change the value to false in runtime and reload the plugin, it could lead into issues with the afk detection.
  enabled: false

  # The time after which a player is considered AFK. You can use the unit-modifier for this.
  # Currently the player will be considered afk after 15 minutes.
  after: '15m'

  # If true, the time that the player is afk, will be removed.
  removeTime: true

  # If true, the player will be kicked after the time specified in 'afk.after'.
  autoKick: true

  # The time how often the plugin checks if a player is afk.
  # The unit for this is seconds.
  repeatCheck: 30

##############
#  Commands  #
##############

# In case you want to add some aliases to the commands, you can do it here.
# There are some given aliases, but you can add or remove them.
command:
  LoriTimeAdmin:
    alias:
      - 'lta'
      - 'ltadmin'
      - 'loritimea'
  LoriTime:
    alias:
      - 'ot'
      - 'lt'
      - 'loritime'
      - 'lorit'
  LoriTimeTop:
    alias:
      - "ttop"
      - "lttop"
      - "ltop"
      - "toptimes"
  Afk:
    alias: [ ]

################
# Integrations #
################
integrations:
  PlaceholderAPI: true
