name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Cache target folder
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ github.run_number }}

      - name: Activate lf line ending check in editorconfig
        run: |
          find . -type f -name ".editorconfig" -exec sed -i "s~#end_of_line = ~end_of_line = ~g" {} \;

      - name: Prepare build variables
        id: prepare-variables
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=loritime.version -q -DforceStdout)
          echo "CURRENT_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Current loritime version: $VERSION"

          # Extract the current build number from the version
          if [[ "${VERSION}" =~ -DEV-([0-9]+)$ ]]; then
            BUILD_NUMBER=${BASH_REMATCH[1]}
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          else
            NEW_BUILD_NUMBER=1
          fi

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            NEW_VERSION="${VERSION/-DEV-UNOFFICIAL/-DEV-ARTIFACT-${{ github.run_number }}}"
          else
            NEW_VERSION="${VERSION/-DEV-UNOFFICIAL/-DEV-${NEW_BUILD_NUMBER}}"
          fi

          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "New loritime version: $NEW_VERSION"

      - name: Set temporary version
        run: |
          sed -i "s/<loritime.version>.*<\/loritime.version>/<loritime.version>${{ env.NEW_VERSION }}<\/loritime.version>/" pom.xml

      - name: Build with updated version
        run: mvn verify

      - name: Restore original version
        run: |
          sed -i "s/<loritime.version>.*<\/loritime.version>/<loritime.version>${{ env.CURRENT_VERSION }}<\/loritime.version>/" pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoriTimeArtifacts
          path: |
            **/target/*.jar
            !config/target/*.jar
