name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Cache target folder
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ github.run_number }}

      - name: Activate lf line ending check in editorconfig
        run: |
          find . -type f -name ".editorconfig" -exec sed -i "s~#end_of_line = ~end_of_line = ~g" {} \;

      - name: Get current version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=loritime.version -q -DforceStdout)
          echo "CURRENT_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Current loritime version: $VERSION"

      - name: Increment version
        id: increment-version
        run: |
          CURRENT_VERSION=${{ env.CURRENT_VERSION }}
          if [[ "$CURRENT_VERSION" == *-DEV-UNOFFICIAL ]]; then
            NEW_VERSION="${CURRENT_VERSION/-DEV-UNOFFICIAL/-DEV-1}"
          elif [[ "$CURRENT_VERSION" =~ -DEV-([0-9]+) ]]; then
            BUILD_NUMBER=${BASH_REMATCH[1]}
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            NEW_VERSION="${CURRENT_VERSION/-DEV-$BUILD_NUMBER/-DEV-$NEW_BUILD_NUMBER}"
          else
            NEW_VERSION="${CURRENT_VERSION}-DEV-1"
          fi
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "New loritime version: $NEW_VERSION"

      - name: Build with updated version
        run: |
          mvn versions:set -DnewVersion=${{ env.NEW_VERSION }} -DgenerateBackupPoms=false
          mvn verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoriTime-Artifacts
          path: |
            **/target/*.jar
            !config/target/*.jar
